/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TokenRouteImport } from './routes/token'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as AppAgentRouteImport } from './routes/_app/agent'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppClippingRouteImport } from './routes/_app/clipping'
import { Route as AppHealthRouteImport } from './routes/_app/health'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppIdeationRouteImport } from './routes/_app/ideation'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppMoneyRouteImport } from './routes/_app/money'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSocialRouteImport } from './routes/_app/social'
import { Route as AppStudioRouteImport } from './routes/_app/studio'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppThumbnailsRouteImport } from './routes/_app/thumbnails'
import { Route as ApiAgencySchemaRouteImport } from './routes/api/agency-schema'
import { Route as ApiDemoRouteImport } from './routes/api/demo'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth.authorize'
import { Route as OauthRegisterRouteImport } from './routes/oauth.register'
import { Route as OauthTokenRouteImport } from './routes/oauth.token'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalActivityRouteImport } from './routes/portal/activity'
import { Route as PortalApprovalsRouteImport } from './routes/portal/approvals'
import { Route as PortalAssetsRouteImport } from './routes/portal/assets'
import { Route as PortalHelpRouteImport } from './routes/portal/help'
import { Route as PortalHomeRouteImport } from './routes/portal/home'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients.index'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients.$clientId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronOpsRouteImport } from './routes/api/cron/ops'
import { Route as ApiLibraryFileRouteImport } from './routes/api/library.file'
import { Route as ApiLibraryUploadRouteImport } from './routes/api/library.upload'
import { Route as ApiOauthLinearRouteImport } from './routes/api/oauth/linear'
import { Route as ApiOauthSocialRouteImport } from './routes/api/oauth/social'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1.$'
import { Route as ApiWebhooksInboundRouteImport } from './routes/api/webhooks/inbound'
import { Route as ApiWebhooksTelegramRouteImport } from './routes/api/webhooks/telegram'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'
import { Route as ApiWebhooksWhopRouteImport } from './routes/api/webhooks/whop'
import { Route as DotwellKnownOauthProtectedResourceApiMcpRouteImport } from './routes/[.]well-known/oauth-protected-resource.api.mcp'
import { Route as ApiMcpDotwellKnownOauthProtectedResourceRouteImport } from './routes/api/mcp.[.]well-known.oauth-protected-resource'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppClippingRoute = AppClippingRouteImport.update({
  id: '/clipping',
  path: '/clipping',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeationRoute = AppIdeationRouteImport.update({
  id: '/ideation',
  path: '/ideation',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyRoute = AppMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppThumbnailsRoute = AppThumbnailsRouteImport.update({
  id: '/thumbnails',
  path: '/thumbnails',
  getParentRoute: () => AppRoute,
} as any)
const ApiAgencySchemaRoute = ApiAgencySchemaRouteImport.update({
  id: '/api/agency-schema',
  path: '/api/agency-schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoRoute = ApiDemoRouteImport.update({
  id: '/api/demo',
  path: '/api/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRegisterRoute = OauthRegisterRouteImport.update({
  id: '/oauth/register',
  path: '/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalActivityRoute = PortalActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApprovalsRoute = PortalApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAssetsRoute = PortalAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHelpRoute = PortalHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHomeRoute = PortalHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronOpsRoute = ApiCronOpsRouteImport.update({
  id: '/api/cron/ops',
  path: '/api/cron/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryFileRoute = ApiLibraryFileRouteImport.update({
  id: '/api/library/file',
  path: '/api/library/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryUploadRoute = ApiLibraryUploadRouteImport.update({
  id: '/api/library/upload',
  path: '/api/library/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthLinearRoute = ApiOauthLinearRouteImport.update({
  id: '/api/oauth/linear',
  path: '/api/oauth/linear',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthSocialRoute = ApiOauthSocialRouteImport.update({
  id: '/api/oauth/social',
  path: '/api/oauth/social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksInboundRoute = ApiWebhooksInboundRouteImport.update({
  id: '/api/webhooks/inbound',
  path: '/api/webhooks/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTelegramRoute = ApiWebhooksTelegramRouteImport.update({
  id: '/api/webhooks/telegram',
  path: '/api/webhooks/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhopRoute = ApiWebhooksWhopRouteImport.update({
  id: '/api/webhooks/whop',
  path: '/api/webhooks/whop',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceApiMcpRoute =
  DotwellKnownOauthProtectedResourceApiMcpRouteImport.update({
    id: '/api/mcp',
    path: '/api/mcp',
    getParentRoute: () => DotwellKnownOauthProtectedResourceRoute,
  } as any)
const ApiMcpDotwellKnownOauthProtectedResourceRoute =
  ApiMcpDotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => ApiMcpRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/token': typeof TokenRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/agent': typeof AppAgentRoute
  '/analytics': typeof AppAnalyticsRoute
  '/approvals': typeof AppApprovalsRoute
  '/billing': typeof AppBillingRoute
  '/calendar': typeof AppCalendarRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/clipping': typeof AppClippingRoute
  '/health': typeof AppHealthRoute
  '/home': typeof AppHomeRoute
  '/ideation': typeof AppIdeationRoute
  '/inbox': typeof AppInboxRoute
  '/leads': typeof AppLeadsRoute
  '/library': typeof AppLibraryRoute
  '/money': typeof AppMoneyRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/studio': typeof AppStudioRoute
  '/team': typeof AppTeamRoute
  '/thumbnails': typeof AppThumbnailsRoute
  '/api/agency-schema': typeof ApiAgencySchemaRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/portal/activity': typeof PortalActivityRoute
  '/portal/approvals': typeof PortalApprovalsRoute
  '/portal/assets': typeof PortalAssetsRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/home': typeof PortalHomeRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/': typeof PortalIndexRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/ops': typeof ApiCronOpsRoute
  '/api/library/file': typeof ApiLibraryFileRoute
  '/api/library/upload': typeof ApiLibraryUploadRoute
  '/api/oauth/linear': typeof ApiOauthLinearRoute
  '/api/oauth/social': typeof ApiOauthSocialRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/webhooks/inbound': typeof ApiWebhooksInboundRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/webhooks/whop': typeof ApiWebhooksWhopRoute
  '/clients/': typeof AppClientsIndexRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/api/mcp/.well-known/oauth-protected-resource': typeof ApiMcpDotwellKnownOauthProtectedResourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/token': typeof TokenRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/agent': typeof AppAgentRoute
  '/analytics': typeof AppAnalyticsRoute
  '/approvals': typeof AppApprovalsRoute
  '/billing': typeof AppBillingRoute
  '/calendar': typeof AppCalendarRoute
  '/clipping': typeof AppClippingRoute
  '/health': typeof AppHealthRoute
  '/home': typeof AppHomeRoute
  '/ideation': typeof AppIdeationRoute
  '/inbox': typeof AppInboxRoute
  '/leads': typeof AppLeadsRoute
  '/library': typeof AppLibraryRoute
  '/money': typeof AppMoneyRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/studio': typeof AppStudioRoute
  '/team': typeof AppTeamRoute
  '/thumbnails': typeof AppThumbnailsRoute
  '/api/agency-schema': typeof ApiAgencySchemaRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/portal/activity': typeof PortalActivityRoute
  '/portal/approvals': typeof PortalApprovalsRoute
  '/portal/assets': typeof PortalAssetsRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/home': typeof PortalHomeRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal': typeof PortalIndexRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/ops': typeof ApiCronOpsRoute
  '/api/library/file': typeof ApiLibraryFileRoute
  '/api/library/upload': typeof ApiLibraryUploadRoute
  '/api/oauth/linear': typeof ApiOauthLinearRoute
  '/api/oauth/social': typeof ApiOauthSocialRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/webhooks/inbound': typeof ApiWebhooksInboundRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/webhooks/whop': typeof ApiWebhooksWhopRoute
  '/clients': typeof AppClientsIndexRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/api/mcp/.well-known/oauth-protected-resource': typeof ApiMcpDotwellKnownOauthProtectedResourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/token': typeof TokenRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/clipping': typeof AppClippingRoute
  '/_app/health': typeof AppHealthRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/ideation': typeof AppIdeationRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/money': typeof AppMoneyRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/studio': typeof AppStudioRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/thumbnails': typeof AppThumbnailsRoute
  '/api/agency-schema': typeof ApiAgencySchemaRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/portal/activity': typeof PortalActivityRoute
  '/portal/approvals': typeof PortalApprovalsRoute
  '/portal/assets': typeof PortalAssetsRoute
  '/portal/help': typeof PortalHelpRoute
  '/portal/home': typeof PortalHomeRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/': typeof PortalIndexRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/ops': typeof ApiCronOpsRoute
  '/api/library/file': typeof ApiLibraryFileRoute
  '/api/library/upload': typeof ApiLibraryUploadRoute
  '/api/oauth/linear': typeof ApiOauthLinearRoute
  '/api/oauth/social': typeof ApiOauthSocialRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/webhooks/inbound': typeof ApiWebhooksInboundRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/webhooks/whop': typeof ApiWebhooksWhopRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/.well-known/oauth-protected-resource/api/mcp': typeof DotwellKnownOauthProtectedResourceApiMcpRoute
  '/api/mcp/.well-known/oauth-protected-resource': typeof ApiMcpDotwellKnownOauthProtectedResourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/docs'
    | '/login'
    | '/portal'
    | '/register'
    | '/reset-password'
    | '/token'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/agent'
    | '/analytics'
    | '/approvals'
    | '/billing'
    | '/calendar'
    | '/clients'
    | '/clipping'
    | '/health'
    | '/home'
    | '/ideation'
    | '/inbox'
    | '/leads'
    | '/library'
    | '/money'
    | '/onboarding'
    | '/settings'
    | '/social'
    | '/studio'
    | '/team'
    | '/thumbnails'
    | '/api/agency-schema'
    | '/api/demo'
    | '/api/health'
    | '/api/mcp'
    | '/oauth/authorize'
    | '/oauth/register'
    | '/oauth/token'
    | '/portal/activity'
    | '/portal/approvals'
    | '/portal/assets'
    | '/portal/help'
    | '/portal/home'
    | '/portal/login'
    | '/portal/'
    | '/clients/$clientId'
    | '/api/auth/$'
    | '/api/cron/ops'
    | '/api/library/file'
    | '/api/library/upload'
    | '/api/oauth/linear'
    | '/api/oauth/social'
    | '/api/v1/$'
    | '/api/webhooks/inbound'
    | '/api/webhooks/telegram'
    | '/api/webhooks/whatsapp'
    | '/api/webhooks/whop'
    | '/clients/'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/api/mcp/.well-known/oauth-protected-resource'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/docs'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/token'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/agent'
    | '/analytics'
    | '/approvals'
    | '/billing'
    | '/calendar'
    | '/clipping'
    | '/health'
    | '/home'
    | '/ideation'
    | '/inbox'
    | '/leads'
    | '/library'
    | '/money'
    | '/onboarding'
    | '/settings'
    | '/social'
    | '/studio'
    | '/team'
    | '/thumbnails'
    | '/api/agency-schema'
    | '/api/demo'
    | '/api/health'
    | '/api/mcp'
    | '/oauth/authorize'
    | '/oauth/register'
    | '/oauth/token'
    | '/portal/activity'
    | '/portal/approvals'
    | '/portal/assets'
    | '/portal/help'
    | '/portal/home'
    | '/portal/login'
    | '/portal'
    | '/clients/$clientId'
    | '/api/auth/$'
    | '/api/cron/ops'
    | '/api/library/file'
    | '/api/library/upload'
    | '/api/oauth/linear'
    | '/api/oauth/social'
    | '/api/v1/$'
    | '/api/webhooks/inbound'
    | '/api/webhooks/telegram'
    | '/api/webhooks/whatsapp'
    | '/api/webhooks/whop'
    | '/clients'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/api/mcp/.well-known/oauth-protected-resource'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/authorize'
    | '/docs'
    | '/login'
    | '/portal'
    | '/register'
    | '/reset-password'
    | '/token'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/.well-known/openid-configuration'
    | '/_app/agent'
    | '/_app/analytics'
    | '/_app/approvals'
    | '/_app/billing'
    | '/_app/calendar'
    | '/_app/clients'
    | '/_app/clipping'
    | '/_app/health'
    | '/_app/home'
    | '/_app/ideation'
    | '/_app/inbox'
    | '/_app/leads'
    | '/_app/library'
    | '/_app/money'
    | '/_app/onboarding'
    | '/_app/settings'
    | '/_app/social'
    | '/_app/studio'
    | '/_app/team'
    | '/_app/thumbnails'
    | '/api/agency-schema'
    | '/api/demo'
    | '/api/health'
    | '/api/mcp'
    | '/oauth/authorize'
    | '/oauth/register'
    | '/oauth/token'
    | '/portal/activity'
    | '/portal/approvals'
    | '/portal/assets'
    | '/portal/help'
    | '/portal/home'
    | '/portal/login'
    | '/portal/'
    | '/_app/clients/$clientId'
    | '/api/auth/$'
    | '/api/cron/ops'
    | '/api/library/file'
    | '/api/library/upload'
    | '/api/oauth/linear'
    | '/api/oauth/social'
    | '/api/v1/$'
    | '/api/webhooks/inbound'
    | '/api/webhooks/telegram'
    | '/api/webhooks/whatsapp'
    | '/api/webhooks/whop'
    | '/_app/clients/'
    | '/.well-known/oauth-protected-resource/api/mcp'
    | '/api/mcp/.well-known/oauth-protected-resource'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthorizeRoute: typeof AuthorizeRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TokenRoute: typeof TokenRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRouteWithChildren
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiAgencySchemaRoute: typeof ApiAgencySchemaRoute
  ApiDemoRoute: typeof ApiDemoRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRouteWithChildren
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthRegisterRoute: typeof OauthRegisterRoute
  OauthTokenRoute: typeof OauthTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronOpsRoute: typeof ApiCronOpsRoute
  ApiLibraryFileRoute: typeof ApiLibraryFileRoute
  ApiLibraryUploadRoute: typeof ApiLibraryUploadRoute
  ApiOauthLinearRoute: typeof ApiOauthLinearRoute
  ApiOauthSocialRoute: typeof ApiOauthSocialRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiWebhooksInboundRoute: typeof ApiWebhooksInboundRoute
  ApiWebhooksTelegramRoute: typeof ApiWebhooksTelegramRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
  ApiWebhooksWhopRoute: typeof ApiWebhooksWhopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clipping': {
      id: '/_app/clipping'
      path: '/clipping'
      fullPath: '/clipping'
      preLoaderRoute: typeof AppClippingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health': {
      id: '/_app/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ideation': {
      id: '/_app/ideation'
      path: '/ideation'
      fullPath: '/ideation'
      preLoaderRoute: typeof AppIdeationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money': {
      id: '/_app/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AppMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/thumbnails': {
      id: '/_app/thumbnails'
      path: '/thumbnails'
      fullPath: '/thumbnails'
      preLoaderRoute: typeof AppThumbnailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/agency-schema': {
      id: '/api/agency-schema'
      path: '/api/agency-schema'
      fullPath: '/api/agency-schema'
      preLoaderRoute: typeof ApiAgencySchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo': {
      id: '/api/demo'
      path: '/api/demo'
      fullPath: '/api/demo'
      preLoaderRoute: typeof ApiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/register': {
      id: '/oauth/register'
      path: '/oauth/register'
      fullPath: '/oauth/register'
      preLoaderRoute: typeof OauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/activity': {
      id: '/portal/activity'
      path: '/activity'
      fullPath: '/portal/activity'
      preLoaderRoute: typeof PortalActivityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/approvals': {
      id: '/portal/approvals'
      path: '/approvals'
      fullPath: '/portal/approvals'
      preLoaderRoute: typeof PortalApprovalsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/assets': {
      id: '/portal/assets'
      path: '/assets'
      fullPath: '/portal/assets'
      preLoaderRoute: typeof PortalAssetsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/help': {
      id: '/portal/help'
      path: '/help'
      fullPath: '/portal/help'
      preLoaderRoute: typeof PortalHelpRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/home': {
      id: '/portal/home'
      path: '/home'
      fullPath: '/portal/home'
      preLoaderRoute: typeof PortalHomeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/ops': {
      id: '/api/cron/ops'
      path: '/api/cron/ops'
      fullPath: '/api/cron/ops'
      preLoaderRoute: typeof ApiCronOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/file': {
      id: '/api/library/file'
      path: '/api/library/file'
      fullPath: '/api/library/file'
      preLoaderRoute: typeof ApiLibraryFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/upload': {
      id: '/api/library/upload'
      path: '/api/library/upload'
      fullPath: '/api/library/upload'
      preLoaderRoute: typeof ApiLibraryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/linear': {
      id: '/api/oauth/linear'
      path: '/api/oauth/linear'
      fullPath: '/api/oauth/linear'
      preLoaderRoute: typeof ApiOauthLinearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/social': {
      id: '/api/oauth/social'
      path: '/api/oauth/social'
      fullPath: '/api/oauth/social'
      preLoaderRoute: typeof ApiOauthSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/inbound': {
      id: '/api/webhooks/inbound'
      path: '/api/webhooks/inbound'
      fullPath: '/api/webhooks/inbound'
      preLoaderRoute: typeof ApiWebhooksInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/telegram': {
      id: '/api/webhooks/telegram'
      path: '/api/webhooks/telegram'
      fullPath: '/api/webhooks/telegram'
      preLoaderRoute: typeof ApiWebhooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whop': {
      id: '/api/webhooks/whop'
      path: '/api/webhooks/whop'
      fullPath: '/api/webhooks/whop'
      preLoaderRoute: typeof ApiWebhooksWhopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource/api/mcp': {
      id: '/.well-known/oauth-protected-resource/api/mcp'
      path: '/api/mcp'
      fullPath: '/.well-known/oauth-protected-resource/api/mcp'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceApiMcpRouteImport
      parentRoute: typeof DotwellKnownOauthProtectedResourceRoute
    }
    '/api/mcp/.well-known/oauth-protected-resource': {
      id: '/api/mcp/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/api/mcp/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof ApiMcpDotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof ApiMcpRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppClippingRoute: typeof AppClippingRoute
  AppHealthRoute: typeof AppHealthRoute
  AppHomeRoute: typeof AppHomeRoute
  AppIdeationRoute: typeof AppIdeationRoute
  AppInboxRoute: typeof AppInboxRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMoneyRoute: typeof AppMoneyRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppStudioRoute: typeof AppStudioRoute
  AppTeamRoute: typeof AppTeamRoute
  AppThumbnailsRoute: typeof AppThumbnailsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppClippingRoute: AppClippingRoute,
  AppHealthRoute: AppHealthRoute,
  AppHomeRoute: AppHomeRoute,
  AppIdeationRoute: AppIdeationRoute,
  AppInboxRoute: AppInboxRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMoneyRoute: AppMoneyRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppStudioRoute: AppStudioRoute,
  AppTeamRoute: AppTeamRoute,
  AppThumbnailsRoute: AppThumbnailsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalActivityRoute: typeof PortalActivityRoute
  PortalApprovalsRoute: typeof PortalApprovalsRoute
  PortalAssetsRoute: typeof PortalAssetsRoute
  PortalHelpRoute: typeof PortalHelpRoute
  PortalHomeRoute: typeof PortalHomeRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalActivityRoute: PortalActivityRoute,
  PortalApprovalsRoute: PortalApprovalsRoute,
  PortalAssetsRoute: PortalAssetsRoute,
  PortalHelpRoute: PortalHelpRoute,
  PortalHomeRoute: PortalHomeRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface DotwellKnownOauthProtectedResourceRouteChildren {
  DotwellKnownOauthProtectedResourceApiMcpRoute: typeof DotwellKnownOauthProtectedResourceApiMcpRoute
}

const DotwellKnownOauthProtectedResourceRouteChildren: DotwellKnownOauthProtectedResourceRouteChildren =
  {
    DotwellKnownOauthProtectedResourceApiMcpRoute:
      DotwellKnownOauthProtectedResourceApiMcpRoute,
  }

const DotwellKnownOauthProtectedResourceRouteWithChildren =
  DotwellKnownOauthProtectedResourceRoute._addFileChildren(
    DotwellKnownOauthProtectedResourceRouteChildren,
  )

interface ApiMcpRouteChildren {
  ApiMcpDotwellKnownOauthProtectedResourceRoute: typeof ApiMcpDotwellKnownOauthProtectedResourceRoute
}

const ApiMcpRouteChildren: ApiMcpRouteChildren = {
  ApiMcpDotwellKnownOauthProtectedResourceRoute:
    ApiMcpDotwellKnownOauthProtectedResourceRoute,
}

const ApiMcpRouteWithChildren =
  ApiMcpRoute._addFileChildren(ApiMcpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthorizeRoute: AuthorizeRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TokenRoute: TokenRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRouteWithChildren,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiAgencySchemaRoute: ApiAgencySchemaRoute,
  ApiDemoRoute: ApiDemoRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRouteWithChildren,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthRegisterRoute: OauthRegisterRoute,
  OauthTokenRoute: OauthTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronOpsRoute: ApiCronOpsRoute,
  ApiLibraryFileRoute: ApiLibraryFileRoute,
  ApiLibraryUploadRoute: ApiLibraryUploadRoute,
  ApiOauthLinearRoute: ApiOauthLinearRoute,
  ApiOauthSocialRoute: ApiOauthSocialRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiWebhooksInboundRoute: ApiWebhooksInboundRoute,
  ApiWebhooksTelegramRoute: ApiWebhooksTelegramRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
  ApiWebhooksWhopRoute: ApiWebhooksWhopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
